### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by lovelyyoshino** [TUI-NICR/deep-orientation#5]
I want to run python inference.py, but i can't find the file weights_valid_0268.hdf5, I hope to get a reply soon. Thank you very much for open source this code and wish you a happy life.

**Comment by blewando** [comment]
Hi @lovelyyoshino,
we are happy to hear that you are interested in our work and code.


> I want to run python inference.py, but i can't find the file weights_valid_0268.hdf5, I hope to get a reply soon. Thank you very much for open source this code and wish you a happy life.

Can you briefly describe exactly what kind of environment you have? Do you use an Anaconda Python environment that is set up as described in the Readme? 
I think I once had a similar problem when I wasn't using Anaconda directly. If I remember correctly, the problem was that the hdf5 version didn't fit the version of the model.
Maybe you can also check the hdf5 version you use.

**Comment by lovelyyoshino** [comment]
Yes, thank you for your reply. I use the ubuntu16.04 system and use the
Anaconda environment. Under the corresponding path, I only found two files,
hdf5.index and hdf5.data, but they all run wrong

Benjamin L. <notifications@github.com> 于2020年4月30日周四 上午4:58写道：

**Comment by blewando** [comment]
I tested everything again on a Linux Mint 19.3 machine (based on Ubuntu 18.04). I checked out the master branch of the repository and created a new conda environment based on Python 3.6:
`
conda create --name env_deep_orientation python=3.6
`

I activated the environment with:
`
conda activate env_deep_orientation
`

This shows me an "(env_deep_orientation)" at the beginning of my bash command line and indicates that the environment is active.  
Then (within the environment) I installed the requirements from the root directory (CPU, since I have no cuda installed) using the following command: 
`
pip install -r requirements_cpu.txt 
`

This should install, among other packages, Tensorflow-1.12.3. 
From the src-directory I can start the application without problems (in CPU mode) using:
```
python inference.py     beyer_mod_relu     ../trained_networks/beyer_mod_relu__depth__126x48__biternion__0_030000__1/weights_valid_0268.hdf5 ../nicr_rgb_d_orientation_data_set_examples/small_patches     --input_type depth --input_preprocessing standardize     --input_height 126     --input_width 48     --output_type biternion --n_samples 1 --cpu
```

> Under the corresponding path, I only found two files, hdf5.index and hdf5.data, but they all run wrong

This is normal. In my installation it is the same. So our original code should be able to read these models.

Can you please try everything I wrote above in a new conda environment with Python 3.6? If there are still problems maybe you can post the output of the list command that shows the versions of all installed packages of your environment (within the activated anaconda environment):
`
conda list
`

**Comment by lovelyyoshino** [comment]
First of all, thank you very much for your reply. I used your GPU
requirement to install. It may be 首先，非常感谢你的回复。我用你的 GPU 安装。它可能是because NVIDIA
因为英伟达 cuda is different, so I did not choose your specific version.  The
following is the error.
[image: image.png]
[image: image.png]
Then I will show you the conda list： 然后我会给你看 conda 列表
[image: image.png]
[image: image.png]

Benjamin L. <notifications@github.com> 于2020年5月3日周日 上午1:35写道：

**Comment by lovelyyoshino** [comment]
First of all, thank you very much for your reply. I used your GPU requirement to install. It may be because NVIDIA cuda is different, so I did not choose your specific version.  The following is the error.
![image](https://user-images.githubusercontent.com/21984530/80897121-2a883800-8d28-11ea-8f96-984e0ebbd0d3.png)
![image](https://user-images.githubusercontent.com/21984530/80897125-307e1900-8d28-11ea-8c30-af20fd5c73a2.png)
Then I will show you the conda list：
![image](https://user-images.githubusercontent.com/21984530/80897132-383dbd80-8d28-11ea-9874-1c088e6fc0bf.png)
![image](https://user-images.githubusercontent.com/21984530/80897134-3bd14480-8d28-11ea-93c2-4e00cc31465a.png)

**Comment by blewando** [comment]
It looks to me that you have created your environment "tensorflow" differently, because you have tensorflow installed in version 2.1.0. Our requirements file should install tensorflow 1.12.3. When I list the packages of my environment, which was created like described in my previous post, I get the following list: 

```
_libgcc_mutex             0.1                        main  
absl-py                   0.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py36_0  
gast                      0.3.3                    pypi_0    pypi
grpcio                    1.28.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
joblib                    0.14.1                   pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markdown                  3.2.1                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
opencv-python             3.4.3.18                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
pip                       20.0.2                   py36_1  
protobuf                  3.11.3                   pypi_0    pypi
python                    3.6.10               hcf32534_1  
readline                  8.0                  h7b6447c_0  
scikit-learn              0.22.2.post1             pypi_0    pypi
setuptools                46.1.3                   py36_0  
sqlite                    3.31.1               h62c20be_1  
tensorboard               1.12.2                   pypi_0    pypi
tensorflow                1.12.3                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
tqdm                      4.45.0                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3 
```

Please note the different package versions. Also note that my environment has much fewer packages installed. Maybe you are using an already existing environment? 
Please try a new, clean environment with tensorflow 1.12.3, created as described above or in our readme file. 

Best regards

**Comment by lovelyyoshino** [comment]
![image](https://user-images.githubusercontent.com/21984530/80988448-1e09f980-8e66-11ea-89e9-8c88546f47bd.png)
Thank you very much for your reply. I have changed to version 1.15.2 now. Because cuda is version 10.1, 1.12.1 cannot be installed, but the corresponding file is still not found. You can use the tree tto show me  what documents do you own？

**Comment by blewando** [comment]
I guess 1.15 is also too new. Please try 1.12 of tensorflow. If your cuda ist not compatible, you can install a different cuda-version into your conda environment with: 

`
conda install cudatoolkit=9.0 cudnn
`

As far as I remember, version 9.0 of the cudatoolkit and the corresponding cudnn should work. Please try that.

If it does not work, maybe you can try the cpu only version at first in order validate that everything works.

**Comment by lovelyyoshino** [comment]
Ok, i will try, but can you show me your trained_networks file. Today,  I
use my classmate computer and find the same wrong in tensorflow 1.13.1?

Benjamin L. <notifications@github.com> 于2020年5月5日周二 下午10:04写道：

**Comment by blewando** [comment]
> Today, I use my classmate computer and find the same wrong in tensorflow 1.13.1?

I guess you have to go with tensorflow 1.12 at the moment. So please try that. 

Question: what branch did you check out? You have to go with the master branch that installs tensorflow 1.12 with pip (see requirements file). I believe the branch with tensorflow 1.15 was generated automatically and will not work.  

> Ok, i will try, but can you show me your trained_networks file. 

I'm not quite sure what you mean exactly. When I do an 'ls' I get the following output:
`weights_valid_0268.hdf5.data-00000-of-00001  weights_valid_0268.hdf5.index`
So I did not change anything after I checked the repository out.

**Comment by lovelyyoshino** [comment]
Ok i got it, thank you very much

Benjamin L. <notifications@github.com> 于2020年5月6日周三 上午3:05写道：

**Comment by blewando** [comment]
Your welcome! So now you can run the inference? :)
Good to hear!

**Comment by lovelyyoshino** [comment]
Thank you very much, it is possible to run, it is recommended that your
team add a change note in ReadMe.md, only supports CUDA9.0

Benjamin L. <notifications@github.com> 于2020年5月6日周三 下午3:32写道：
